[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/L_FlightTest.L_FlightTest
EditorStartupMap=/Game/Maps/L_FlightTest.L_FlightTest
GlobalDefaultGameMode=/Script/ExecutiveOps.EOGameModeBase

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/ExecutiveOps")

; Enhanced Input is the only input path in this project.
[/Script/Engine.InputSettings]
DefaultPlayerInputClass=/Script/EnhancedInput.EnhancedPlayerInput
DefaultInputComponentClass=/Script/EnhancedInput.EnhancedInputComponent
bEnableMouseSmoothing=False

[/Script/EngineSettings.GeneralProjectSettings]
ProjectName=Executive Ops
ProjectID=(A=0,B=0,C=0,D=0)

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12

[/Script/Engine.RendererSettings]
r.DefaultFeature.AutoExposure=False
r.Nanite.ProjectEnabled=True
r.Lumen.HardwareRayTracing=False
